---
title: "Homework 6"
author: "Alice Tivarovsky"
date: "11/16/2019"
output: html_document
---

Setup code: 

```{r setup}
library(tidyverse)

set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```

## Problem 1

Loading and tidying data: 

```{r}
bwt_data = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = as_factor(babysex),
    frace = as_factor(frace),
    malform = as_factor(malform), 
    mrace = as_factor(mrace)
  ) 

```
The resulting dataset contains 4342 observations across 20 variables. Numerical  variables were converted to categorical variables based on the data dictionary using as_factor. 

Checking for missing values using purrr: 
```{r}
bwt_data %>% 
  map_df(~sum(is.na(.)))
```

We confirm there are no missing values in the dataset. 